# General
name: "Biocomputing 2016"
description: "Peer-led Introduction to Computational Biology"
url: http://localhost:4000

markdown: redcarpet
highlighter: pygments

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"