# General
name: "Biocomputing 2016"
description: "Peer-led Introduction to Computational Biology"
baseurl: "https://ccbbatut.github.io/Biocomputing_Spring2016"
future: true


markdown: redcarpet
highlighter: pygments

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"